# This is a basic workflow to help you get started with Actions

name: Build for dev(ios・android)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: 
      - 'develop/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh 3.16.2

      - name: fix git 9148
        run: git config --global url."https://".insteadOf git://

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - run: flutter pub get
      - run: flutter pub run intl_utils:generate
      
      # - name: Install the Apple certificate and provisioning profile
      #   run: |
      #     # create variables

      #     # create temporary keychain


      #     # import certificate to keychain


      #     # apply provisioning profile
  

      - name: make apk
        run: flutter build apk --release --flavor dev --target=lib/main-development.dart --build-number=${GITHUB_RUN_NUMBER}
      
      # - name: make ipa
      #   run: flutter build ipa --release --flavor dev --target=lib/main-development.dart --export-options-plist=tools/dev/ExportOptions.plist --build-number=${GITHUB_RUN_NUMBER}

      # - name: make manifest
      #   run: |
      #     sed -i "" "s/GITHUB_RUN_NUMBER/${GITHUB_RUN_NUMBER}/g" tools/dev/manifest.plist

      - name: file tree
        run: pwd;find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'
      
